-- Strict payment system — run once in the Supabase SQL editor (Jul 17 2026).
-- One row per issued sales document (quote / agreement / invoice). The pay
-- page (cappvcs.com/pay) only accepts numbers that exist in this table.
-- Rows are pushed automatically by the Sales Docs tool on Generate, or added
-- manually in the admin panel (for docs issued before this system existed).
create table if not exists capp_sales_docs (
    id                bigint generated by default as identity primary key,
    number            text not null unique,          -- stored UPPERCASE, e.g. INV-20260717-001
    doc_type          text not null default 'invoice',  -- quote | agreement | invoice
    school            text not null,
    description       text default '',
    amount_cents      integer not null check (amount_cents > 0),
    status            text not null default 'unpaid',   -- unpaid | paid | void
    stripe_session_id text,
    created_at        timestamptz not null default now(),
    paid_at           timestamptz
);

-- Service-role access only (the Render server); no anon policies.
alter table capp_sales_docs enable row level security;
