# -*- mode: python ; coding: utf-8 -*-
# Bundles the Visio Converter's font toolkit (visio_to_ppt.py + Fonts) INTO the
# EXE as data files under "VisioToPPT_bundle" — capp_binder_converter.py reads
# it from sys._MEIPASS at runtime. Sourced straight from the original folder
# so there's no stale duplicate to keep in sync.
import os
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

_VTP_SRC = r"C:\Users\roger.hayhurst.ctr\VisioToPPT"

datas = [
    (_VTP_SRC + r"\visio_to_ppt.py", "VisioToPPT_bundle"),
    # ⚠ Fonts go to <MEIPASS>/Fonts, NOT under VisioToPPT_bundle. The toolkit
    # font_dirs() looks only in app_dir()/Fonts and <MEIPASS>/Fonts, so bundling
    # them one level deeper meant register_session_fonts() found NOTHING and
    # logged "loaded 0 bundled font file(s)" -- 34 fonts shipped inside the EXE
    # and not one of them usable (Aug 19 2026).
    (_VTP_SRC + r"\Fonts", "Fonts"),
]
datas += collect_data_files("pptx")

a = Analysis(
    ["capp_binder_converter.py"],
    pathex=[],
    binaries=[],
    datas=datas,
    # ⚠ collect_data_files("pptx") above bundles python-pptx's TEMPLATES but
    # none of its MODULES. That leaves a pptx/ directory of pure data in the
    # bundle, which Python then treats as an empty NAMESPACE package -- hence
    # the runtime failure "cannot import name 'Presentation' from 'pptx'
    # (unknown location)". "unknown location" is the tell for exactly this.
    # The converter caught it and carried on with "converter toolkit NOT loaded
    # -- font protections off, plain export only", so PowerPoint output was
    # silently degraded rather than failing (Aug 19 2026).
    # PyQt6: the bundled font toolkit (visio_to_ppt.py) imports QtCore/QtGui/
    # QtWidgets at module level for its own GUI. Nothing here uses that GUI, but
    # the converter calls vtp.ConvertWorker._font_family_names, and that class
    # subclasses QThread -- so the module cannot import at all without Qt, and
    # the whole toolkit was silently skipped ("No module named 'PyQt6'"),
    # leaving font protections off and PowerPoint output on plain export in
    # EVERY build ever shipped. Costs ~50 MB; playbook font fidelity is worth it.
    hiddenimports=(["win32com", "win32timezone", "fitz",
                    "PyQt6.QtCore", "PyQt6.QtGui", "PyQt6.QtWidgets"]
                   + collect_submodules("pptx")),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["torch", "torchaudio", "torchvision", "pygame", "tensorflow", "cv2", "customtkinter", "tkinter"],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="CAPP_Binder_Converter",
    # Windows version resource, generated by build_converter.ps1 from
    # CONVERTER_VERSION. Without it the EXE carries NO version at all, so
    # two copies on a coach's machine are indistinguishable in Explorer --
    # which is exactly how a July build kept claiming jobs a month later
    # (Aug 19 2026). Guarded so a build still works if the file is absent.
    version="converter_version_info.txt" if os.path.exists("converter_version_info.txt") else None,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # fully invisible — no window, no console, ever
    disable_windowed_traceback=True,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=r"T:\CAPP_FINAL\capplogo.ico",
)
